-- === ESQUEMA aguaravulka + datos migrados ===
-- Correr en Supabase: SQL Editor -> New query -> pegar todo -> Run

-- Categorías
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('aguara','Training','uploads/opt/SJD_3638-2.webp',0);
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('aguara','Running','uploads/opt/63.webp',1);
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('aguara','Ciclismo','uploads/opt/PAT07304.webp',2);
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('aguara','Casual deportiva','uploads/opt/45.webp',3);
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('aguara','Court Sports','uploads/opt/SJD_3019-scaled.webp',4);
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('vulka','Casual','uploads/opt/vk-chaleco-beige.webp',0);
insert into aguaravulka.categorias (marca,nombre,imagen,orden) values ('vulka','Oficina','uploads/opt/vk-chaleco-gris.webp',1);

-- Productos
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'AGUARA CRUX TOP',140000,'XS · S · M · G · XG',null,false,'uploads/opt/SJD_3638-2.webp',0);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'AGUARA FLOW CLASSIC',190000,'XS · S · M · G · XG',null,false,'uploads/opt/3.webp',1);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Court Sports' limit 1),'AGUARA FLOW SKIRT',160000,'XS · S · M · G · XG',null,false,'uploads/opt/SJD_3019-scaled.webp',2);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'AGUARA FLOW TOP',150000,'XS · S · M · G · XG',null,false,'uploads/opt/SJD_3014-scaled.webp',3);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Court Sports' limit 1),'AGUARA GLOW SKIRT',160000,'XS · S · M · G · XG',null,false,'uploads/opt/Historia-de-Instagram-Frase-Mate-de-Mate-Minimalista-Blanco-y-Negro.webp',4);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'AGUARA PULSE + UV',160000,'XS · S · M · G · XG',null,false,'uploads/opt/63.webp',5);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'AGUARA TOP SECURE',150000,'XS · S · M · G · XG',null,false,'uploads/opt/SJD_2966-scaled.webp',6);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'BOLSO AGUARA',80000,'Único',null,false,'uploads/opt/45.webp',7);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Camisillas Cotton Fem',120000,'XS · S · M · G · XG',null,false,'uploads/opt/cottonAguara01.webp',8);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'Camisilla Ligera Pro Run',110000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT03613-scaled.webp',9);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'Camisilla Pro Run',140000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT03708-scaled.webp',10);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Campera Aguara Training',190000,'XS · S · M · G · XG',null,true,'uploads/opt/PAT06271-1.webp',11);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Camisilla Cotton Flow',125000,'XS · S · M · G · XG',null,false,'uploads/opt/carmen-blanco01.webp',12);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Ciclismo' limit 1),'Chaleco Aguara Bike',210000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT07304.webp',13);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Chaqueta Aguara Sport',210000,'XS · S · M · G · XG',null,true,'uploads/opt/PAT06674.webp',14);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Ciclismo' limit 1),'Ciclista Medio',159000,'XS · S · M · G · XG',null,false,'uploads/opt/ciclistamedio04.webp',15);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Ciclismo' limit 1),'Ciclista Corto',150000,'XS · S · M · G · XG',null,false,'uploads/opt/ciclistacorto03.webp',16);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Ciclismo' limit 1),'Ciclista Pro Run',140000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT03705-scaled.webp',17);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Ciclismo' limit 1),'Ciclista Stride Cargo',150000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT03542-scaled.webp',18);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Enterizo Aguara Clasico',390000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT06741-1.webp',19);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'ENTERIZO AGUARA LUMEN OVAL',190000,'XS · S · M · G · XG',null,false,'uploads/opt/46.webp',20);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'ENTERIZO AGUARA LUMEN TIRA',190000,'XS · S · M · G · XG',null,false,'uploads/opt/27.webp',21);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Enterizo Aguara Pata Ancha',390000,'XS · S · M · G · XG',null,true,'uploads/opt/PAT06616.webp',22);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Gift Card',100000,'Monto a elegir','[100000, 200000, 300000, 350000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000]'::jsonb,false,'uploads/opt/giftcard-real.webp',23);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Pantalón Strai AGUARÁ',160000,'XS · S · M · G · XG',null,false,'uploads/opt/40.webp',24);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Legging Aguara Oxford',280000,'XS · S · M · G · XG',null,true,'uploads/opt/PAT03661-scaled.webp',25);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Legging Clásico',260000,'XS · S · M · G · XG',null,false,'uploads/opt/54.webp',26);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Legging Cruzado',260000,'XS · S · M · G · XG',null,false,'uploads/opt/topEmma01.webp',27);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Musculosa AFLC',125000,'XS · S · M · G · XG',null,false,'uploads/opt/aflc01.webp',28);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Musculosa Cotton Masc',130000,'XS · S · M · G · XG',null,false,'uploads/opt/cottonMasc01.webp',29);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Oversize Urban Aguara',160000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT03691-scaled.webp',30);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Pantalón Aguara Training',140000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT06277.webp',31);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'PULLOVER NACIONAL',220000,'XS · S · M · G · XG',null,false,'uploads/opt/ChatGPT-Image-16-jun-2026-04_00_54-p.m.webp',32);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Pupera',115000,'XS · S · M · G · XG',null,false,'uploads/opt/pupera01.webp',33);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Remera Aguara',135000,'XS · S · M · G · XG',null,false,'uploads/opt/SJD_8577.webp',34);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'Remera Dry Fit Lisa',90000,'XS · S · M · G · XG',null,false,'uploads/opt/dryFit01.webp',35);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'Remera Premium',120000,'XS · S · M · G · XG',null,false,'uploads/opt/SJD_8538.webp',36);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Short Cross',112000,'XS · S · M · G · XG',null,false,'uploads/opt/shortCross02.webp',37);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'Short Running Freedom',150000,'XS · S · M · G · XG',null,false,'uploads/opt/8-7.webp',38);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'Short Running',150000,'XS · S · M · G · XG',null,false,'uploads/opt/shortRunning01.webp',39);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Casual deportiva' limit 1),'SUDADERA ESSENCE AGUARA',190000,'XS · S · M · G · XG',null,false,'uploads/opt/25.webp',40);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Top Aguara Aura',160000,'XS · S · M · G · XG',null,true,'uploads/opt/PAT07019-scaled.webp',41);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Top Aguara Classic',160000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT06720.webp',42);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Top Aguara Sport',160000,'XS · S · M · G · XG',null,true,'uploads/opt/PAT06926-scaled.webp',43);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Top Deportivo Clásico',150000,'XS · S · M · G · XG',null,false,'uploads/opt/topClasico01.webp',44);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Top Deportivo Corrugado',145000,'XS · S · M · G · XG',null,false,'uploads/opt/topCorrugado08.webp',45);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Training' limit 1),'Top Deportivo Cuello Alto Corto',130000,'XS · S · M · G · XG',null,false,'uploads/opt/topCuelloAlto01.webp',46);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('aguara',(select id from aguaravulka.categorias where marca='aguara' and nombre='Running' limit 1),'Top Stride Pocket',160000,'XS · S · M · G · XG',null,false,'uploads/opt/PAT03539-scaled.webp',47);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Blusa Dama Crep Milena Blanco',146000,'XP · P · M · G · XG · 2XG',null,false,null,48);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Blusa Dama Crep Milena Celeste',146000,'XP · P · M · G · XG · 2XG',null,false,null,49);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Blusa Dama Crep Milena Rosa Vieja',146000,'XP · P · M · G · XG · 2XG',null,false,null,50);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Chaleco Classic Dama Lino Beige',172500,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-chaleco-beige.webp',51);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Chaleco Classic Dama Lino Negro',172500,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-chaleco-negro.webp',52);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Chaleco Cruzado Dama De Vestir Gris',196250,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-chaleco-gris.webp',53);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Chaleco Classic Dama De Vestir Marron',187500,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-chaleco-marron.webp',54);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Chaleco Esp. Abierto Dama Lino Marfil',172500,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-chaleco-marfil.webp',55);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Chaleco Esp. Abierto Dama Lino Blanco R',172500,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-chaleco-blanco.webp',56);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Pantalon Ancho De Vestir Dama Marron',169600,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-pantalon-marron.webp',57);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Pantalon Ancho De Vestir Dama Gris',169600,'XP · P · M · G · XG · 2XG',null,false,null,58);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Pantalon Ancho De Vestir Dama Azul Marino R',169600,'XP · P · M · G · XG · 2XG',null,false,null,59);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Short De Lino Dama Negro R',126000,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-short-negro.webp',60);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Short De Lino Dama Beige R',126000,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-short-beige.webp',61);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Short De Lino Dama Blanco R',126000,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-short-beige.webp',62);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Casual' limit 1),'Short De Lino Dama Marfil R',126000,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-short-beige.webp',63);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Blazer Sastre Classic Dama Azul Marino R',330000,'XP · P · M · G · XG · 2XG',null,false,'uploads/opt/vk-blazer-navy.webp',64);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Blazer Sastre Classic Dama Gris',330000,'XP · P · M · G · XG · 2XG',null,false,null,65);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Blazer Sastre Classic Dama Marron',330000,'XP · P · M · G · XG · 2XG',null,false,null,66);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Camisa Clasica Rayas Dama Azul',180000,'XP · P · M · G · XG · 2XG',null,false,null,67);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Camisa Clasica Rayas Dama Rosa',180000,'XP · P · M · G · XG · 2XG',null,false,null,68);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Camisa Clasica Rayas Dama Verde',180000,'XP · P · M · G · XG · 2XG',null,false,null,69);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Camisa Clasica Rayas Dama Blanco',180000,'XP · P · M · G · XG · 2XG',null,false,null,70);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Camisa Clasica Dama Rosa',180000,'XP · P · M · G · XG · 2XG',null,false,null,71);
insert into aguaravulka.productos (marca,categoria_id,nombre,precio,talles,montos,destacado,imagen,orden) values ('vulka',(select id from aguaravulka.categorias where marca='vulka' and nombre='Oficina' limit 1),'Camisa Clasica Rayas Caballero Celeste',185000,'XP · P · M · G · XG · 2XG',null,false,null,72);

-- Galería inicial (imagen principal como primera foto)
insert into aguaravulka.producto_imagenes (producto_id,url,orden) select id, imagen, 0 from aguaravulka.productos where imagen is not null;

-- Portadas / Hero
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('aguara','SI ELEGÍS\nMOVERTE','TRAINING','uploads/opt/PAT06737.webp','50% 22%',0);
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('aguara','JUGÁ TU\nJUEGO','COURT SPORTS','uploads/opt/SJD_3072.webp','50% 25%',1);
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('aguara','ENTRENÁ\nSIN LÍMITES','TRAINING','uploads/opt/PAT06786.webp','50% 20%',2);
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('aguara','TU RITMO,\nTU REGLA','AIRE LIBRE','uploads/opt/SJD_2997.webp','50% 26%',3);
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('aguara','HECHO EN\nPARAGUAY','CASUAL','uploads/opt/SJD_2896.webp','50% 22%',4);
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('aguara','COLECCIÓN\nEN MOVIMIENTO','COLECCIÓN','uploads/opt/SJD_3728.webp','50% 25%',5);
insert into aguaravulka.portada_slides (marca,titulo,etiqueta,imagen,pos,orden) values ('vulka','Tu mejor versión sigue siendo vos','NUEVA TEMPORADA','uploads/opt/vulka-hero.webp','50% 26%',0);