-- Pedidos web (pagos con PagoPar). OPCIONAL: solo si querés que los pedidos
-- pagados queden registrados. El cobro funciona igual sin esto.
-- Correr en Supabase -> SQL Editor.

create table if not exists aguaravulka.web_pedidos (
  id                 bigint generated by default as identity primary key,
  id_pedido_comercio bigint,
  cliente_nombre     text,
  cliente_email      text,
  cliente_telefono   text,
  cliente_documento  text,
  ciudad_codigo      text,
  direccion          text,
  modalidad          text default 'envio',
  observaciones      text,
  subtotal           bigint default 0,
  envio              bigint default 0,
  total              bigint default 0,
  estado_pago        text default 'pendiente',
  estado_envio       text default 'pendiente',
  pagopar_hash       text,
  pagopar_link       text,
  pagopar_forma_pago text,
  pagado_at          timestamptz,
  creado_at          timestamptz not null default now()
);

create index if not exists web_pedidos_hash_idx on aguaravulka.web_pedidos (pagopar_hash);
create index if not exists web_pedidos_estado_idx on aguaravulka.web_pedidos (estado_pago);

create table if not exists aguaravulka.web_pedido_items (
  id               bigint generated by default as identity primary key,
  pedido_id        bigint not null references aguaravulka.web_pedidos (id) on delete cascade,
  producto_codigo  text,
  nombre           text,
  color            text,
  cantidad         int default 1,
  precio_unitario  bigint default 0,
  total_linea      bigint default 0
);

create index if not exists web_pedido_items_pedido_idx on aguaravulka.web_pedido_items (pedido_id);

-- RLS: el backend escribe con service_role (bypassa RLS). Dejamos las tablas
-- con RLS activo y SIN políticas públicas: nadie anónimo puede leer/escribir.
alter table aguaravulka.web_pedidos enable row level security;
alter table aguaravulka.web_pedido_items enable row level security;

-- Lectura para usuarios autenticados (panel de admin), por si querés listarlos.
drop policy if exists web_pedidos_auth_read on aguaravulka.web_pedidos;
create policy web_pedidos_auth_read on aguaravulka.web_pedidos for select to authenticated using (true);
drop policy if exists web_pedido_items_auth_read on aguaravulka.web_pedido_items;
create policy web_pedido_items_auth_read on aguaravulka.web_pedido_items for select to authenticated using (true);

notify pgrst, 'reload schema';
