// Generado desde "PLANILLA DE PRODUCTOS 2026 - ACTUALIZADO.xlsx" — sin datos inventados.
export const VULKA = [
  {
    "id": "VLK-11001",
    "sku": "VLK-11001",
    "b": "vulka",
    "name": "Blusa Dama Crep Milena Blanco",
    "cat": "Casual",
    "price": 146000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11007",
    "sku": "VLK-11007",
    "b": "vulka",
    "name": "Blusa Dama Crep Milena Celeste",
    "cat": "Casual",
    "price": 146000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11013",
    "sku": "VLK-11013",
    "b": "vulka",
    "name": "Blusa Dama Crep Milena Rosa Vieja",
    "cat": "Casual",
    "price": 146000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11019",
    "img": "uploads/opt/vk-chaleco-beige.webp",
    "sku": "VLK-11019",
    "b": "vulka",
    "name": "Chaleco Classic Dama Lino Beige",
    "cat": "Casual",
    "price": 172500,
    "stock": 131,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11025",
    "img": "uploads/opt/vk-chaleco-negro.webp",
    "sku": "VLK-11025",
    "b": "vulka",
    "name": "Chaleco Classic Dama Lino Negro",
    "cat": "Casual",
    "price": 172500,
    "stock": 131,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11031",
    "img": "uploads/opt/vk-chaleco-gris.webp",
    "sku": "VLK-11031",
    "b": "vulka",
    "name": "Chaleco Cruzado Dama De Vestir Gris",
    "cat": "Oficina",
    "price": 196250,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11037",
    "img": "uploads/opt/vk-chaleco-marron.webp",
    "sku": "VLK-11037",
    "b": "vulka",
    "name": "Chaleco Classic Dama De Vestir Marron",
    "cat": "Oficina",
    "price": 187500,
    "stock": 124,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11043",
    "img": "uploads/opt/vk-chaleco-marfil.webp",
    "sku": "VLK-11043",
    "b": "vulka",
    "name": "Chaleco Esp. Abierto Dama Lino Marfil",
    "cat": "Casual",
    "price": 172500,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11049",
    "img": "uploads/opt/vk-chaleco-blanco.webp",
    "sku": "VLK-11049",
    "b": "vulka",
    "name": "Chaleco Esp. Abierto Dama Lino Blanco R",
    "cat": "Casual",
    "price": 172500,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11055",
    "img": "uploads/opt/vk-pantalon-marron.webp",
    "sku": "VLK-11055",
    "b": "vulka",
    "name": "Pantalon Ancho De Vestir Dama Marron",
    "cat": "Oficina",
    "price": 169600,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11061",
    "sku": "VLK-11061",
    "b": "vulka",
    "name": "Pantalon Ancho De Vestir Dama Gris",
    "cat": "Oficina",
    "price": 169600,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11067",
    "sku": "VLK-11067",
    "b": "vulka",
    "name": "Pantalon Ancho De Vestir Dama Azul Marino R",
    "cat": "Oficina",
    "price": 169600,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11073",
    "img": "uploads/opt/vk-short-negro.webp",
    "sku": "VLK-11073",
    "b": "vulka",
    "name": "Short De Lino Dama Negro R",
    "cat": "Casual",
    "price": 126000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11079",
    "img": "uploads/opt/vk-short-beige.webp",
    "sku": "VLK-11079",
    "b": "vulka",
    "name": "Short De Lino Dama Beige R",
    "cat": "Casual",
    "price": 126000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11085",
    "img": "uploads/opt/vk-short-beige.webp",
    "sku": "VLK-11085",
    "b": "vulka",
    "name": "Short De Lino Dama Blanco R",
    "cat": "Casual",
    "price": 126000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11091",
    "img": "uploads/opt/vk-short-beige.webp",
    "sku": "VLK-11091",
    "b": "vulka",
    "name": "Short De Lino Dama Marfil R",
    "cat": "Casual",
    "price": 126000,
    "stock": 106,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11097",
    "img": "uploads/opt/vk-blazer-navy.webp",
    "sku": "VLK-11097",
    "b": "vulka",
    "name": "Blazer Sastre Classic Dama Azul Marino R",
    "cat": "Oficina",
    "price": 330000,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11103",
    "sku": "VLK-11103",
    "b": "vulka",
    "name": "Blazer Sastre Classic Dama Gris",
    "cat": "Oficina",
    "price": 330000,
    "stock": 151,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11109",
    "sku": "VLK-11109",
    "b": "vulka",
    "name": "Blazer Sastre Classic Dama Marron",
    "cat": "Oficina",
    "price": 330000,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11115",
    "sku": "VLK-11115",
    "b": "vulka",
    "name": "Camisa Clasica Rayas Dama Azul",
    "cat": "Oficina",
    "price": 180000,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11121",
    "sku": "VLK-11121",
    "b": "vulka",
    "name": "Camisa Clasica Rayas Dama Rosa",
    "cat": "Oficina",
    "price": 180000,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11127",
    "sku": "VLK-11127",
    "b": "vulka",
    "name": "Camisa Clasica Rayas Dama Verde",
    "cat": "Oficina",
    "price": 180000,
    "stock": 93,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11133",
    "sku": "VLK-11133",
    "b": "vulka",
    "name": "Camisa Clasica Rayas Dama Blanco",
    "cat": "Oficina",
    "price": 180000,
    "stock": 122,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11139",
    "sku": "VLK-11139",
    "b": "vulka",
    "name": "Camisa Clasica Dama Rosa",
    "cat": "Oficina",
    "price": 180000,
    "stock": 93,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  },
  {
    "id": "VLK-11145",
    "sku": "VLK-11145",
    "b": "vulka",
    "name": "Camisa Clasica Rayas Caballero Celeste",
    "cat": "Oficina",
    "price": 185000,
    "stock": 123,
    "tipo": "Femenino",
    "sizes": "XP · P · M · G · XG · 2XG"
  }
];
